//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPB.Negocio.WS_SAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="WS_SAP.ZWS_SAPLETRA_GGB")]
    public interface ZWS_SAPLETRA_GGB {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z_DAMEPROVEEDORES_GGB no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse1 Z_DAMEPROVEEDORES_GGB(GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse1> Z_DAMEPROVEEDORES_GGBAsync(GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z_CREAR_GASTOS_VENTAS_SIDER no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse1 Z_CREAR_GASTOS_VENTAS_SIDER(GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse1> Z_CREAR_GASTOS_VENTAS_SIDERAsync(GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z_CREAR_TRANS_VENTAS_SIDER no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse1 Z_CREAR_TRANS_VENTAS_SIDER(GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse1> Z_CREAR_TRANS_VENTAS_SIDERAsync(GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_DAMEPROVEEDORES_GGB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_SOCIEDADField;
        
        private LFA1[] t_PROVEEDORESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string E_SOCIEDAD {
            get {
                return this.e_SOCIEDADField;
            }
            set {
                this.e_SOCIEDADField = value;
                this.RaisePropertyChanged("E_SOCIEDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public LFA1[] T_PROVEEDORES {
            get {
                return this.t_PROVEEDORESField;
            }
            set {
                this.t_PROVEEDORESField = value;
                this.RaisePropertyChanged("T_PROVEEDORES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class LFA1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string lIFNRField;
        
        private string lAND1Field;
        
        private string nAME1Field;
        
        private string nAME2Field;
        
        private string nAME3Field;
        
        private string nAME4Field;
        
        private string oRT01Field;
        
        private string oRT02Field;
        
        private string pFACHField;
        
        private string pSTL2Field;
        
        private string pSTLZField;
        
        private string rEGIOField;
        
        private string sORTLField;
        
        private string sTRASField;
        
        private string aDRNRField;
        
        private string mCOD1Field;
        
        private string mCOD2Field;
        
        private string mCOD3Field;
        
        private string aNREDField;
        
        private string bAHNSField;
        
        private string bBBNRField;
        
        private string bBSNRField;
        
        private string bEGRUField;
        
        private string bRSCHField;
        
        private string bUBKZField;
        
        private string dATLTField;
        
        private string dTAMSField;
        
        private string dTAWSField;
        
        private string eRDATField;
        
        private string eRNAMField;
        
        private string eSRNRField;
        
        private string kONZSField;
        
        private string kTOKKField;
        
        private string kUNNRField;
        
        private string lNRZAField;
        
        private string lOEVMField;
        
        private string sPERRField;
        
        private string sPERMField;
        
        private string sPRASField;
        
        private string sTCD1Field;
        
        private string sTCD2Field;
        
        private string sTKZAField;
        
        private string sTKZUField;
        
        private string tELBXField;
        
        private string tELF1Field;
        
        private string tELF2Field;
        
        private string tELFXField;
        
        private string tELTXField;
        
        private string tELX1Field;
        
        private string xCPDKField;
        
        private string xZEMPField;
        
        private string vBUNDField;
        
        private string fISKNField;
        
        private string sTCEGField;
        
        private string sTKZNField;
        
        private string sPERQField;
        
        private string gBORTField;
        
        private string gBDATField;
        
        private string sEXKZField;
        
        private string kRAUSField;
        
        private string rEVDBField;
        
        private string qSSYSField;
        
        private string kTOCKField;
        
        private string pFORTField;
        
        private string wERKSField;
        
        private string lTSNAField;
        
        private string wERKRField;
        
        private string pLKALField;
        
        private string dUEFLField;
        
        private string tXJCDField;
        
        private string sPERZField;
        
        private string sCACDField;
        
        private string sFRGRField;
        
        private string lZONEField;
        
        private string xLFZAField;
        
        private string dLGRPField;
        
        private string fITYPField;
        
        private string sTCDTField;
        
        private string rEGSSField;
        
        private string aCTSSField;
        
        private string sTCD3Field;
        
        private string sTCD4Field;
        
        private string sTCD5Field;
        
        private string iPISPField;
        
        private string tAXBSField;
        
        private string pROFSField;
        
        private string sTGDLField;
        
        private string eMNFRField;
        
        private string lFURLField;
        
        private string j_1KFREPREField;
        
        private string j_1KFTBUSField;
        
        private string j_1KFTINDField;
        
        private string cONFSField;
        
        private string uPDATField;
        
        private System.DateTime uPTIMField;
        
        private string nODELField;
        
        private string qSSYSDATField;
        
        private string pODKZBField;
        
        private string fISKUField;
        
        private string sTENRField;
        
        private string cARRIER_CONFField;
        
        private string mIN_COMPField;
        
        private string tERM_LIField;
        
        private string cRC_NUMField;
        
        private decimal j_SC_CAPITALField;
        
        private string j_SC_CURRENCYField;
        
        private string aLCField;
        
        private string pMT_OFFICEField;
        
        private string pSOFGField;
        
        private string pSOISField;
        
        private string pSON1Field;
        
        private string pSON2Field;
        
        private string pSON3Field;
        
        private string pSOVNField;
        
        private string pSOTLField;
        
        private string pSOHSField;
        
        private string pSOSTField;
        
        private string tRANSPORT_CHAINField;
        
        private decimal sTAGING_TIMEField;
        
        private string sCHEDULING_TYPEField;
        
        private string sUBMI_RELEVANTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LAND1 {
            get {
                return this.lAND1Field;
            }
            set {
                this.lAND1Field = value;
                this.RaisePropertyChanged("LAND1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
                this.RaisePropertyChanged("NAME1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NAME2 {
            get {
                return this.nAME2Field;
            }
            set {
                this.nAME2Field = value;
                this.RaisePropertyChanged("NAME2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NAME3 {
            get {
                return this.nAME3Field;
            }
            set {
                this.nAME3Field = value;
                this.RaisePropertyChanged("NAME3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NAME4 {
            get {
                return this.nAME4Field;
            }
            set {
                this.nAME4Field = value;
                this.RaisePropertyChanged("NAME4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ORT01 {
            get {
                return this.oRT01Field;
            }
            set {
                this.oRT01Field = value;
                this.RaisePropertyChanged("ORT01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ORT02 {
            get {
                return this.oRT02Field;
            }
            set {
                this.oRT02Field = value;
                this.RaisePropertyChanged("ORT02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PFACH {
            get {
                return this.pFACHField;
            }
            set {
                this.pFACHField = value;
                this.RaisePropertyChanged("PFACH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PSTL2 {
            get {
                return this.pSTL2Field;
            }
            set {
                this.pSTL2Field = value;
                this.RaisePropertyChanged("PSTL2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PSTLZ {
            get {
                return this.pSTLZField;
            }
            set {
                this.pSTLZField = value;
                this.RaisePropertyChanged("PSTLZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string REGIO {
            get {
                return this.rEGIOField;
            }
            set {
                this.rEGIOField = value;
                this.RaisePropertyChanged("REGIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SORTL {
            get {
                return this.sORTLField;
            }
            set {
                this.sORTLField = value;
                this.RaisePropertyChanged("SORTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string STRAS {
            get {
                return this.sTRASField;
            }
            set {
                this.sTRASField = value;
                this.RaisePropertyChanged("STRAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ADRNR {
            get {
                return this.aDRNRField;
            }
            set {
                this.aDRNRField = value;
                this.RaisePropertyChanged("ADRNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string MCOD1 {
            get {
                return this.mCOD1Field;
            }
            set {
                this.mCOD1Field = value;
                this.RaisePropertyChanged("MCOD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string MCOD2 {
            get {
                return this.mCOD2Field;
            }
            set {
                this.mCOD2Field = value;
                this.RaisePropertyChanged("MCOD2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string MCOD3 {
            get {
                return this.mCOD3Field;
            }
            set {
                this.mCOD3Field = value;
                this.RaisePropertyChanged("MCOD3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ANRED {
            get {
                return this.aNREDField;
            }
            set {
                this.aNREDField = value;
                this.RaisePropertyChanged("ANRED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string BAHNS {
            get {
                return this.bAHNSField;
            }
            set {
                this.bAHNSField = value;
                this.RaisePropertyChanged("BAHNS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string BBBNR {
            get {
                return this.bBBNRField;
            }
            set {
                this.bBBNRField = value;
                this.RaisePropertyChanged("BBBNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string BBSNR {
            get {
                return this.bBSNRField;
            }
            set {
                this.bBSNRField = value;
                this.RaisePropertyChanged("BBSNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string BEGRU {
            get {
                return this.bEGRUField;
            }
            set {
                this.bEGRUField = value;
                this.RaisePropertyChanged("BEGRU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string BRSCH {
            get {
                return this.bRSCHField;
            }
            set {
                this.bRSCHField = value;
                this.RaisePropertyChanged("BRSCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string BUBKZ {
            get {
                return this.bUBKZField;
            }
            set {
                this.bUBKZField = value;
                this.RaisePropertyChanged("BUBKZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string DATLT {
            get {
                return this.dATLTField;
            }
            set {
                this.dATLTField = value;
                this.RaisePropertyChanged("DATLT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string DTAMS {
            get {
                return this.dTAMSField;
            }
            set {
                this.dTAMSField = value;
                this.RaisePropertyChanged("DTAMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string DTAWS {
            get {
                return this.dTAWSField;
            }
            set {
                this.dTAWSField = value;
                this.RaisePropertyChanged("DTAWS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string ERDAT {
            get {
                return this.eRDATField;
            }
            set {
                this.eRDATField = value;
                this.RaisePropertyChanged("ERDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string ERNAM {
            get {
                return this.eRNAMField;
            }
            set {
                this.eRNAMField = value;
                this.RaisePropertyChanged("ERNAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string ESRNR {
            get {
                return this.eSRNRField;
            }
            set {
                this.eSRNRField = value;
                this.RaisePropertyChanged("ESRNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string KONZS {
            get {
                return this.kONZSField;
            }
            set {
                this.kONZSField = value;
                this.RaisePropertyChanged("KONZS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string KTOKK {
            get {
                return this.kTOKKField;
            }
            set {
                this.kTOKKField = value;
                this.RaisePropertyChanged("KTOKK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
                this.RaisePropertyChanged("KUNNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string LNRZA {
            get {
                return this.lNRZAField;
            }
            set {
                this.lNRZAField = value;
                this.RaisePropertyChanged("LNRZA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string LOEVM {
            get {
                return this.lOEVMField;
            }
            set {
                this.lOEVMField = value;
                this.RaisePropertyChanged("LOEVM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string SPERR {
            get {
                return this.sPERRField;
            }
            set {
                this.sPERRField = value;
                this.RaisePropertyChanged("SPERR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string SPERM {
            get {
                return this.sPERMField;
            }
            set {
                this.sPERMField = value;
                this.RaisePropertyChanged("SPERM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string SPRAS {
            get {
                return this.sPRASField;
            }
            set {
                this.sPRASField = value;
                this.RaisePropertyChanged("SPRAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string STCD1 {
            get {
                return this.sTCD1Field;
            }
            set {
                this.sTCD1Field = value;
                this.RaisePropertyChanged("STCD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string STCD2 {
            get {
                return this.sTCD2Field;
            }
            set {
                this.sTCD2Field = value;
                this.RaisePropertyChanged("STCD2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string STKZA {
            get {
                return this.sTKZAField;
            }
            set {
                this.sTKZAField = value;
                this.RaisePropertyChanged("STKZA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string STKZU {
            get {
                return this.sTKZUField;
            }
            set {
                this.sTKZUField = value;
                this.RaisePropertyChanged("STKZU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string TELBX {
            get {
                return this.tELBXField;
            }
            set {
                this.tELBXField = value;
                this.RaisePropertyChanged("TELBX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string TELF1 {
            get {
                return this.tELF1Field;
            }
            set {
                this.tELF1Field = value;
                this.RaisePropertyChanged("TELF1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string TELF2 {
            get {
                return this.tELF2Field;
            }
            set {
                this.tELF2Field = value;
                this.RaisePropertyChanged("TELF2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string TELFX {
            get {
                return this.tELFXField;
            }
            set {
                this.tELFXField = value;
                this.RaisePropertyChanged("TELFX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string TELTX {
            get {
                return this.tELTXField;
            }
            set {
                this.tELTXField = value;
                this.RaisePropertyChanged("TELTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string TELX1 {
            get {
                return this.tELX1Field;
            }
            set {
                this.tELX1Field = value;
                this.RaisePropertyChanged("TELX1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string XCPDK {
            get {
                return this.xCPDKField;
            }
            set {
                this.xCPDKField = value;
                this.RaisePropertyChanged("XCPDK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string XZEMP {
            get {
                return this.xZEMPField;
            }
            set {
                this.xZEMPField = value;
                this.RaisePropertyChanged("XZEMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string VBUND {
            get {
                return this.vBUNDField;
            }
            set {
                this.vBUNDField = value;
                this.RaisePropertyChanged("VBUND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string FISKN {
            get {
                return this.fISKNField;
            }
            set {
                this.fISKNField = value;
                this.RaisePropertyChanged("FISKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string STCEG {
            get {
                return this.sTCEGField;
            }
            set {
                this.sTCEGField = value;
                this.RaisePropertyChanged("STCEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string STKZN {
            get {
                return this.sTKZNField;
            }
            set {
                this.sTKZNField = value;
                this.RaisePropertyChanged("STKZN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string SPERQ {
            get {
                return this.sPERQField;
            }
            set {
                this.sPERQField = value;
                this.RaisePropertyChanged("SPERQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string GBORT {
            get {
                return this.gBORTField;
            }
            set {
                this.gBORTField = value;
                this.RaisePropertyChanged("GBORT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string GBDAT {
            get {
                return this.gBDATField;
            }
            set {
                this.gBDATField = value;
                this.RaisePropertyChanged("GBDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string SEXKZ {
            get {
                return this.sEXKZField;
            }
            set {
                this.sEXKZField = value;
                this.RaisePropertyChanged("SEXKZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string KRAUS {
            get {
                return this.kRAUSField;
            }
            set {
                this.kRAUSField = value;
                this.RaisePropertyChanged("KRAUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string REVDB {
            get {
                return this.rEVDBField;
            }
            set {
                this.rEVDBField = value;
                this.RaisePropertyChanged("REVDB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string QSSYS {
            get {
                return this.qSSYSField;
            }
            set {
                this.qSSYSField = value;
                this.RaisePropertyChanged("QSSYS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string KTOCK {
            get {
                return this.kTOCKField;
            }
            set {
                this.kTOCKField = value;
                this.RaisePropertyChanged("KTOCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string PFORT {
            get {
                return this.pFORTField;
            }
            set {
                this.pFORTField = value;
                this.RaisePropertyChanged("PFORT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string LTSNA {
            get {
                return this.lTSNAField;
            }
            set {
                this.lTSNAField = value;
                this.RaisePropertyChanged("LTSNA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string WERKR {
            get {
                return this.wERKRField;
            }
            set {
                this.wERKRField = value;
                this.RaisePropertyChanged("WERKR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string PLKAL {
            get {
                return this.pLKALField;
            }
            set {
                this.pLKALField = value;
                this.RaisePropertyChanged("PLKAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string DUEFL {
            get {
                return this.dUEFLField;
            }
            set {
                this.dUEFLField = value;
                this.RaisePropertyChanged("DUEFL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string TXJCD {
            get {
                return this.tXJCDField;
            }
            set {
                this.tXJCDField = value;
                this.RaisePropertyChanged("TXJCD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string SPERZ {
            get {
                return this.sPERZField;
            }
            set {
                this.sPERZField = value;
                this.RaisePropertyChanged("SPERZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string SCACD {
            get {
                return this.sCACDField;
            }
            set {
                this.sCACDField = value;
                this.RaisePropertyChanged("SCACD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string SFRGR {
            get {
                return this.sFRGRField;
            }
            set {
                this.sFRGRField = value;
                this.RaisePropertyChanged("SFRGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string LZONE {
            get {
                return this.lZONEField;
            }
            set {
                this.lZONEField = value;
                this.RaisePropertyChanged("LZONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=75)]
        public string XLFZA {
            get {
                return this.xLFZAField;
            }
            set {
                this.xLFZAField = value;
                this.RaisePropertyChanged("XLFZA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=76)]
        public string DLGRP {
            get {
                return this.dLGRPField;
            }
            set {
                this.dLGRPField = value;
                this.RaisePropertyChanged("DLGRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=77)]
        public string FITYP {
            get {
                return this.fITYPField;
            }
            set {
                this.fITYPField = value;
                this.RaisePropertyChanged("FITYP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=78)]
        public string STCDT {
            get {
                return this.sTCDTField;
            }
            set {
                this.sTCDTField = value;
                this.RaisePropertyChanged("STCDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=79)]
        public string REGSS {
            get {
                return this.rEGSSField;
            }
            set {
                this.rEGSSField = value;
                this.RaisePropertyChanged("REGSS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=80)]
        public string ACTSS {
            get {
                return this.aCTSSField;
            }
            set {
                this.aCTSSField = value;
                this.RaisePropertyChanged("ACTSS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=81)]
        public string STCD3 {
            get {
                return this.sTCD3Field;
            }
            set {
                this.sTCD3Field = value;
                this.RaisePropertyChanged("STCD3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=82)]
        public string STCD4 {
            get {
                return this.sTCD4Field;
            }
            set {
                this.sTCD4Field = value;
                this.RaisePropertyChanged("STCD4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=83)]
        public string STCD5 {
            get {
                return this.sTCD5Field;
            }
            set {
                this.sTCD5Field = value;
                this.RaisePropertyChanged("STCD5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=84)]
        public string IPISP {
            get {
                return this.iPISPField;
            }
            set {
                this.iPISPField = value;
                this.RaisePropertyChanged("IPISP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=85)]
        public string TAXBS {
            get {
                return this.tAXBSField;
            }
            set {
                this.tAXBSField = value;
                this.RaisePropertyChanged("TAXBS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=86)]
        public string PROFS {
            get {
                return this.pROFSField;
            }
            set {
                this.pROFSField = value;
                this.RaisePropertyChanged("PROFS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=87)]
        public string STGDL {
            get {
                return this.sTGDLField;
            }
            set {
                this.sTGDLField = value;
                this.RaisePropertyChanged("STGDL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=88)]
        public string EMNFR {
            get {
                return this.eMNFRField;
            }
            set {
                this.eMNFRField = value;
                this.RaisePropertyChanged("EMNFR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=89)]
        public string LFURL {
            get {
                return this.lFURLField;
            }
            set {
                this.lFURLField = value;
                this.RaisePropertyChanged("LFURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=90)]
        public string J_1KFREPRE {
            get {
                return this.j_1KFREPREField;
            }
            set {
                this.j_1KFREPREField = value;
                this.RaisePropertyChanged("J_1KFREPRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=91)]
        public string J_1KFTBUS {
            get {
                return this.j_1KFTBUSField;
            }
            set {
                this.j_1KFTBUSField = value;
                this.RaisePropertyChanged("J_1KFTBUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=92)]
        public string J_1KFTIND {
            get {
                return this.j_1KFTINDField;
            }
            set {
                this.j_1KFTINDField = value;
                this.RaisePropertyChanged("J_1KFTIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=93)]
        public string CONFS {
            get {
                return this.cONFSField;
            }
            set {
                this.cONFSField = value;
                this.RaisePropertyChanged("CONFS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=94)]
        public string UPDAT {
            get {
                return this.uPDATField;
            }
            set {
                this.uPDATField = value;
                this.RaisePropertyChanged("UPDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=95)]
        public System.DateTime UPTIM {
            get {
                return this.uPTIMField;
            }
            set {
                this.uPTIMField = value;
                this.RaisePropertyChanged("UPTIM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=96)]
        public string NODEL {
            get {
                return this.nODELField;
            }
            set {
                this.nODELField = value;
                this.RaisePropertyChanged("NODEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=97)]
        public string QSSYSDAT {
            get {
                return this.qSSYSDATField;
            }
            set {
                this.qSSYSDATField = value;
                this.RaisePropertyChanged("QSSYSDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=98)]
        public string PODKZB {
            get {
                return this.pODKZBField;
            }
            set {
                this.pODKZBField = value;
                this.RaisePropertyChanged("PODKZB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=99)]
        public string FISKU {
            get {
                return this.fISKUField;
            }
            set {
                this.fISKUField = value;
                this.RaisePropertyChanged("FISKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=100)]
        public string STENR {
            get {
                return this.sTENRField;
            }
            set {
                this.sTENRField = value;
                this.RaisePropertyChanged("STENR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=101)]
        public string CARRIER_CONF {
            get {
                return this.cARRIER_CONFField;
            }
            set {
                this.cARRIER_CONFField = value;
                this.RaisePropertyChanged("CARRIER_CONF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=102)]
        public string MIN_COMP {
            get {
                return this.mIN_COMPField;
            }
            set {
                this.mIN_COMPField = value;
                this.RaisePropertyChanged("MIN_COMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=103)]
        public string TERM_LI {
            get {
                return this.tERM_LIField;
            }
            set {
                this.tERM_LIField = value;
                this.RaisePropertyChanged("TERM_LI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=104)]
        public string CRC_NUM {
            get {
                return this.cRC_NUMField;
            }
            set {
                this.cRC_NUMField = value;
                this.RaisePropertyChanged("CRC_NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=105)]
        public decimal J_SC_CAPITAL {
            get {
                return this.j_SC_CAPITALField;
            }
            set {
                this.j_SC_CAPITALField = value;
                this.RaisePropertyChanged("J_SC_CAPITAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=106)]
        public string J_SC_CURRENCY {
            get {
                return this.j_SC_CURRENCYField;
            }
            set {
                this.j_SC_CURRENCYField = value;
                this.RaisePropertyChanged("J_SC_CURRENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=107)]
        public string ALC {
            get {
                return this.aLCField;
            }
            set {
                this.aLCField = value;
                this.RaisePropertyChanged("ALC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=108)]
        public string PMT_OFFICE {
            get {
                return this.pMT_OFFICEField;
            }
            set {
                this.pMT_OFFICEField = value;
                this.RaisePropertyChanged("PMT_OFFICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=109)]
        public string PSOFG {
            get {
                return this.pSOFGField;
            }
            set {
                this.pSOFGField = value;
                this.RaisePropertyChanged("PSOFG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=110)]
        public string PSOIS {
            get {
                return this.pSOISField;
            }
            set {
                this.pSOISField = value;
                this.RaisePropertyChanged("PSOIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=111)]
        public string PSON1 {
            get {
                return this.pSON1Field;
            }
            set {
                this.pSON1Field = value;
                this.RaisePropertyChanged("PSON1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=112)]
        public string PSON2 {
            get {
                return this.pSON2Field;
            }
            set {
                this.pSON2Field = value;
                this.RaisePropertyChanged("PSON2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=113)]
        public string PSON3 {
            get {
                return this.pSON3Field;
            }
            set {
                this.pSON3Field = value;
                this.RaisePropertyChanged("PSON3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=114)]
        public string PSOVN {
            get {
                return this.pSOVNField;
            }
            set {
                this.pSOVNField = value;
                this.RaisePropertyChanged("PSOVN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=115)]
        public string PSOTL {
            get {
                return this.pSOTLField;
            }
            set {
                this.pSOTLField = value;
                this.RaisePropertyChanged("PSOTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=116)]
        public string PSOHS {
            get {
                return this.pSOHSField;
            }
            set {
                this.pSOHSField = value;
                this.RaisePropertyChanged("PSOHS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=117)]
        public string PSOST {
            get {
                return this.pSOSTField;
            }
            set {
                this.pSOSTField = value;
                this.RaisePropertyChanged("PSOST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=118)]
        public string TRANSPORT_CHAIN {
            get {
                return this.tRANSPORT_CHAINField;
            }
            set {
                this.tRANSPORT_CHAINField = value;
                this.RaisePropertyChanged("TRANSPORT_CHAIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=119)]
        public decimal STAGING_TIME {
            get {
                return this.sTAGING_TIMEField;
            }
            set {
                this.sTAGING_TIMEField = value;
                this.RaisePropertyChanged("STAGING_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=120)]
        public string SCHEDULING_TYPE {
            get {
                return this.sCHEDULING_TYPEField;
            }
            set {
                this.sCHEDULING_TYPEField = value;
                this.RaisePropertyChanged("SCHEDULING_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=121)]
        public string SUBMI_RELEVANT {
            get {
                return this.sUBMI_RELEVANTField;
            }
            set {
                this.sUBMI_RELEVANTField = value;
                this.RaisePropertyChanged("SUBMI_RELEVANT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_EXPEDICIONES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string mATNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private int rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_DAMEPROVEEDORES_GGBResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LFA1[] t_PROVEEDORESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public LFA1[] T_PROVEEDORES {
            get {
                return this.t_PROVEEDORESField;
            }
            set {
                this.t_PROVEEDORESField = value;
                this.RaisePropertyChanged("T_PROVEEDORES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_DAMEPROVEEDORES_GGBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGB Z_DAMEPROVEEDORES_GGB;
        
        public Z_DAMEPROVEEDORES_GGBRequest() {
        }
        
        public Z_DAMEPROVEEDORES_GGBRequest(GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGB Z_DAMEPROVEEDORES_GGB) {
            this.Z_DAMEPROVEEDORES_GGB = Z_DAMEPROVEEDORES_GGB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_DAMEPROVEEDORES_GGBResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse Z_DAMEPROVEEDORES_GGBResponse;
        
        public Z_DAMEPROVEEDORES_GGBResponse1() {
        }
        
        public Z_DAMEPROVEEDORES_GGBResponse1(GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse Z_DAMEPROVEEDORES_GGBResponse) {
            this.Z_DAMEPROVEEDORES_GGBResponse = Z_DAMEPROVEEDORES_GGBResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_GASTOS_VENTAS_SIDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPIRET2[] iT_RETURNField;
        
        private string i_TRANSPORTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] IT_RETURN {
            get {
                return this.iT_RETURNField;
            }
            set {
                this.iT_RETURNField = value;
                this.RaisePropertyChanged("IT_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_TRANSPORTE {
            get {
                return this.i_TRANSPORTEField;
            }
            set {
                this.i_TRANSPORTEField = value;
                this.RaisePropertyChanged("I_TRANSPORTE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_GASTOS_VENTAS_SIDERResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_GASTOField;
        
        private BAPIRET2[] iT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string E_GASTO {
            get {
                return this.e_GASTOField;
            }
            set {
                this.e_GASTOField = value;
                this.RaisePropertyChanged("E_GASTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] IT_RETURN {
            get {
                return this.iT_RETURNField;
            }
            set {
                this.iT_RETURNField = value;
                this.RaisePropertyChanged("IT_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_GASTOS_VENTAS_SIDERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDER Z_CREAR_GASTOS_VENTAS_SIDER;
        
        public Z_CREAR_GASTOS_VENTAS_SIDERRequest() {
        }
        
        public Z_CREAR_GASTOS_VENTAS_SIDERRequest(GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDER Z_CREAR_GASTOS_VENTAS_SIDER) {
            this.Z_CREAR_GASTOS_VENTAS_SIDER = Z_CREAR_GASTOS_VENTAS_SIDER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_GASTOS_VENTAS_SIDERResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse Z_CREAR_GASTOS_VENTAS_SIDERResponse;
        
        public Z_CREAR_GASTOS_VENTAS_SIDERResponse1() {
        }
        
        public Z_CREAR_GASTOS_VENTAS_SIDERResponse1(GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse Z_CREAR_GASTOS_VENTAS_SIDERResponse) {
            this.Z_CREAR_GASTOS_VENTAS_SIDERResponse = Z_CREAR_GASTOS_VENTAS_SIDERResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_TRANS_VENTAS_SIDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSD_EXPEDICIONES[] iT_EXPEDICIONESField;
        
        private BAPIRET2[] iT_RETURNField;
        
        private string i_INCO1Field;
        
        private string i_INCO2Field;
        
        private string i_PUESTOField;
        
        private string i_TIPOField;
        
        private string i_TRANSPORTISTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_EXPEDICIONES[] IT_EXPEDICIONES {
            get {
                return this.iT_EXPEDICIONESField;
            }
            set {
                this.iT_EXPEDICIONESField = value;
                this.RaisePropertyChanged("IT_EXPEDICIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] IT_RETURN {
            get {
                return this.iT_RETURNField;
            }
            set {
                this.iT_RETURNField = value;
                this.RaisePropertyChanged("IT_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_INCO1 {
            get {
                return this.i_INCO1Field;
            }
            set {
                this.i_INCO1Field = value;
                this.RaisePropertyChanged("I_INCO1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_INCO2 {
            get {
                return this.i_INCO2Field;
            }
            set {
                this.i_INCO2Field = value;
                this.RaisePropertyChanged("I_INCO2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_PUESTO {
            get {
                return this.i_PUESTOField;
            }
            set {
                this.i_PUESTOField = value;
                this.RaisePropertyChanged("I_PUESTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_TIPO {
            get {
                return this.i_TIPOField;
            }
            set {
                this.i_TIPOField = value;
                this.RaisePropertyChanged("I_TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_TRANSPORTISTA {
            get {
                return this.i_TRANSPORTISTAField;
            }
            set {
                this.i_TRANSPORTISTAField = value;
                this.RaisePropertyChanged("I_TRANSPORTISTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_TRANS_VENTAS_SIDERResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_TRANSPORTEField;
        
        private ZSD_EXPEDICIONES[] iT_EXPEDICIONESField;
        
        private BAPIRET2[] iT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string E_TRANSPORTE {
            get {
                return this.e_TRANSPORTEField;
            }
            set {
                this.e_TRANSPORTEField = value;
                this.RaisePropertyChanged("E_TRANSPORTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_EXPEDICIONES[] IT_EXPEDICIONES {
            get {
                return this.iT_EXPEDICIONESField;
            }
            set {
                this.iT_EXPEDICIONESField = value;
                this.RaisePropertyChanged("IT_EXPEDICIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] IT_RETURN {
            get {
                return this.iT_RETURNField;
            }
            set {
                this.iT_RETURNField = value;
                this.RaisePropertyChanged("IT_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_TRANS_VENTAS_SIDERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDER Z_CREAR_TRANS_VENTAS_SIDER;
        
        public Z_CREAR_TRANS_VENTAS_SIDERRequest() {
        }
        
        public Z_CREAR_TRANS_VENTAS_SIDERRequest(GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDER Z_CREAR_TRANS_VENTAS_SIDER) {
            this.Z_CREAR_TRANS_VENTAS_SIDER = Z_CREAR_TRANS_VENTAS_SIDER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_TRANS_VENTAS_SIDERResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse Z_CREAR_TRANS_VENTAS_SIDERResponse;
        
        public Z_CREAR_TRANS_VENTAS_SIDERResponse1() {
        }
        
        public Z_CREAR_TRANS_VENTAS_SIDERResponse1(GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse Z_CREAR_TRANS_VENTAS_SIDERResponse) {
            this.Z_CREAR_TRANS_VENTAS_SIDERResponse = Z_CREAR_TRANS_VENTAS_SIDERResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_SAPLETRA_GGBChannel : GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_SAPLETRA_GGBClient : System.ServiceModel.ClientBase<GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB>, GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB {
        
        public ZWS_SAPLETRA_GGBClient() {
        }
        
        public ZWS_SAPLETRA_GGBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_SAPLETRA_GGBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SAPLETRA_GGBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SAPLETRA_GGBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse1 GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB.Z_DAMEPROVEEDORES_GGB(GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBRequest request) {
            return base.Channel.Z_DAMEPROVEEDORES_GGB(request);
        }
        
        public GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse Z_DAMEPROVEEDORES_GGB(GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGB Z_DAMEPROVEEDORES_GGB1) {
            GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBRequest inValue = new GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBRequest();
            inValue.Z_DAMEPROVEEDORES_GGB = Z_DAMEPROVEEDORES_GGB1;
            GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse1 retVal = ((GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB)(this)).Z_DAMEPROVEEDORES_GGB(inValue);
            return retVal.Z_DAMEPROVEEDORES_GGBResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse1> GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB.Z_DAMEPROVEEDORES_GGBAsync(GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBRequest request) {
            return base.Channel.Z_DAMEPROVEEDORES_GGBAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBResponse1> Z_DAMEPROVEEDORES_GGBAsync(GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGB Z_DAMEPROVEEDORES_GGB) {
            GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBRequest inValue = new GPB.Negocio.WS_SAP.Z_DAMEPROVEEDORES_GGBRequest();
            inValue.Z_DAMEPROVEEDORES_GGB = Z_DAMEPROVEEDORES_GGB;
            return ((GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB)(this)).Z_DAMEPROVEEDORES_GGBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse1 GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB.Z_CREAR_GASTOS_VENTAS_SIDER(GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERRequest request) {
            return base.Channel.Z_CREAR_GASTOS_VENTAS_SIDER(request);
        }
        
        public GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse Z_CREAR_GASTOS_VENTAS_SIDER(GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDER Z_CREAR_GASTOS_VENTAS_SIDER1) {
            GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERRequest inValue = new GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERRequest();
            inValue.Z_CREAR_GASTOS_VENTAS_SIDER = Z_CREAR_GASTOS_VENTAS_SIDER1;
            GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse1 retVal = ((GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_GASTOS_VENTAS_SIDER(inValue);
            return retVal.Z_CREAR_GASTOS_VENTAS_SIDERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse1> GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB.Z_CREAR_GASTOS_VENTAS_SIDERAsync(GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERRequest request) {
            return base.Channel.Z_CREAR_GASTOS_VENTAS_SIDERAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERResponse1> Z_CREAR_GASTOS_VENTAS_SIDERAsync(GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDER Z_CREAR_GASTOS_VENTAS_SIDER) {
            GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERRequest inValue = new GPB.Negocio.WS_SAP.Z_CREAR_GASTOS_VENTAS_SIDERRequest();
            inValue.Z_CREAR_GASTOS_VENTAS_SIDER = Z_CREAR_GASTOS_VENTAS_SIDER;
            return ((GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_GASTOS_VENTAS_SIDERAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse1 GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB.Z_CREAR_TRANS_VENTAS_SIDER(GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERRequest request) {
            return base.Channel.Z_CREAR_TRANS_VENTAS_SIDER(request);
        }
        
        public GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse Z_CREAR_TRANS_VENTAS_SIDER(GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDER Z_CREAR_TRANS_VENTAS_SIDER1) {
            GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERRequest inValue = new GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERRequest();
            inValue.Z_CREAR_TRANS_VENTAS_SIDER = Z_CREAR_TRANS_VENTAS_SIDER1;
            GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse1 retVal = ((GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_TRANS_VENTAS_SIDER(inValue);
            return retVal.Z_CREAR_TRANS_VENTAS_SIDERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse1> GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB.Z_CREAR_TRANS_VENTAS_SIDERAsync(GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERRequest request) {
            return base.Channel.Z_CREAR_TRANS_VENTAS_SIDERAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERResponse1> Z_CREAR_TRANS_VENTAS_SIDERAsync(GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDER Z_CREAR_TRANS_VENTAS_SIDER) {
            GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERRequest inValue = new GPB.Negocio.WS_SAP.Z_CREAR_TRANS_VENTAS_SIDERRequest();
            inValue.Z_CREAR_TRANS_VENTAS_SIDER = Z_CREAR_TRANS_VENTAS_SIDER;
            return ((GPB.Negocio.WS_SAP.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_TRANS_VENTAS_SIDERAsync(inValue);
        }
    }
}
