//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGN.Negocio.WS_SAP_UNI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="WS_SAP_UNI.ZWS_SAPLETRA_GGB")]
    public interface ZWS_SAPLETRA_GGB {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z_CREAR_PROVEEDOR_GGB no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SAPLETRA_GGB:Z_CREAR_PROVEEDOR_GGBRequ" +
            "est", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse1 Z_CREAR_PROVEEDOR_GGB(SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SAPLETRA_GGB:Z_CREAR_PROVEEDOR_GGBRequ" +
            "est", ReplyAction="*")]
        System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse1> Z_CREAR_PROVEEDOR_GGBAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z_CREAR_TRANS_VENTAS_SIDER no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SAPLETRA_GGB:Z_CREAR_TRANS_VENTAS_SIDE" +
            "RRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse1 Z_CREAR_TRANS_VENTAS_SIDER(SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SAPLETRA_GGB:Z_CREAR_TRANS_VENTAS_SIDE" +
            "RRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse1> Z_CREAR_TRANS_VENTAS_SIDERAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z_CREAR_GASTOS_VENTAS_SIDER no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SAPLETRA_GGB:Z_CREAR_GASTOS_VENTAS_SID" +
            "ERRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse1 Z_CREAR_GASTOS_VENTAS_SIDER(SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SAPLETRA_GGB:Z_CREAR_GASTOS_VENTAS_SID" +
            "ERRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse1> Z_CREAR_GASTOS_VENTAS_SIDERAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z_DAMEPROVEEDORES_GGB no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SAPLETRA_GGB:Z_DAMEPROVEEDORES_GGBRequ" +
            "est", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse1 Z_DAMEPROVEEDORES_GGB(SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SAPLETRA_GGB:Z_DAMEPROVEEDORES_GGBRequ" +
            "est", ReplyAction="*")]
        System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse1> Z_DAMEPROVEEDORES_GGBAsync(SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_PROVEEDOR_GGB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODPOSTALField;
        
        private string dIRECCIONField;
        
        private string nIFField;
        
        private string nOMBREField;
        
        private string pOBLACIONField;
        
        private string sOCIEDADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CODPOSTAL {
            get {
                return this.cODPOSTALField;
            }
            set {
                this.cODPOSTALField = value;
                this.RaisePropertyChanged("CODPOSTAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
                this.RaisePropertyChanged("DIRECCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NIF {
            get {
                return this.nIFField;
            }
            set {
                this.nIFField = value;
                this.RaisePropertyChanged("NIF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string POBLACION {
            get {
                return this.pOBLACIONField;
            }
            set {
                this.pOBLACIONField = value;
                this.RaisePropertyChanged("POBLACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SOCIEDAD {
            get {
                return this.sOCIEDADField;
            }
            set {
                this.sOCIEDADField = value;
                this.RaisePropertyChanged("SOCIEDAD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPROVEEDORGGB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lIFNRField;
        
        private string nAME1Field;
        
        private string pARVWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
                this.RaisePropertyChanged("NAME1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PARVW {
            get {
                return this.pARVWField;
            }
            set {
                this.pARVWField = value;
                this.RaisePropertyChanged("PARVW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private int rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_EXPEDICIONES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string mATNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_PROVEEDOR_GGBResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_PROVEEDOR_GGBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGB Z_CREAR_PROVEEDOR_GGB;
        
        public Z_CREAR_PROVEEDOR_GGBRequest() {
        }
        
        public Z_CREAR_PROVEEDOR_GGBRequest(SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGB Z_CREAR_PROVEEDOR_GGB) {
            this.Z_CREAR_PROVEEDOR_GGB = Z_CREAR_PROVEEDOR_GGB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_PROVEEDOR_GGBResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse Z_CREAR_PROVEEDOR_GGBResponse;
        
        public Z_CREAR_PROVEEDOR_GGBResponse1() {
        }
        
        public Z_CREAR_PROVEEDOR_GGBResponse1(SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse Z_CREAR_PROVEEDOR_GGBResponse) {
            this.Z_CREAR_PROVEEDOR_GGBResponse = Z_CREAR_PROVEEDOR_GGBResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_TRANS_VENTAS_SIDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSD_EXPEDICIONES[] iT_EXPEDICIONESField;
        
        private BAPIRET2[] iT_RETURNField;
        
        private string i_INCO1Field;
        
        private string i_INCO2Field;
        
        private string i_PUESTOField;
        
        private string i_TIPOField;
        
        private string i_TRANSPORTISTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_EXPEDICIONES[] IT_EXPEDICIONES {
            get {
                return this.iT_EXPEDICIONESField;
            }
            set {
                this.iT_EXPEDICIONESField = value;
                this.RaisePropertyChanged("IT_EXPEDICIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] IT_RETURN {
            get {
                return this.iT_RETURNField;
            }
            set {
                this.iT_RETURNField = value;
                this.RaisePropertyChanged("IT_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string I_INCO1 {
            get {
                return this.i_INCO1Field;
            }
            set {
                this.i_INCO1Field = value;
                this.RaisePropertyChanged("I_INCO1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string I_INCO2 {
            get {
                return this.i_INCO2Field;
            }
            set {
                this.i_INCO2Field = value;
                this.RaisePropertyChanged("I_INCO2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string I_PUESTO {
            get {
                return this.i_PUESTOField;
            }
            set {
                this.i_PUESTOField = value;
                this.RaisePropertyChanged("I_PUESTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string I_TIPO {
            get {
                return this.i_TIPOField;
            }
            set {
                this.i_TIPOField = value;
                this.RaisePropertyChanged("I_TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string I_TRANSPORTISTA {
            get {
                return this.i_TRANSPORTISTAField;
            }
            set {
                this.i_TRANSPORTISTAField = value;
                this.RaisePropertyChanged("I_TRANSPORTISTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_TRANS_VENTAS_SIDERResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_TRANSPORTEField;
        
        private ZSD_EXPEDICIONES[] iT_EXPEDICIONESField;
        
        private BAPIRET2[] iT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string E_TRANSPORTE {
            get {
                return this.e_TRANSPORTEField;
            }
            set {
                this.e_TRANSPORTEField = value;
                this.RaisePropertyChanged("E_TRANSPORTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_EXPEDICIONES[] IT_EXPEDICIONES {
            get {
                return this.iT_EXPEDICIONESField;
            }
            set {
                this.iT_EXPEDICIONESField = value;
                this.RaisePropertyChanged("IT_EXPEDICIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] IT_RETURN {
            get {
                return this.iT_RETURNField;
            }
            set {
                this.iT_RETURNField = value;
                this.RaisePropertyChanged("IT_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_TRANS_VENTAS_SIDERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDER Z_CREAR_TRANS_VENTAS_SIDER;
        
        public Z_CREAR_TRANS_VENTAS_SIDERRequest() {
        }
        
        public Z_CREAR_TRANS_VENTAS_SIDERRequest(SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDER Z_CREAR_TRANS_VENTAS_SIDER) {
            this.Z_CREAR_TRANS_VENTAS_SIDER = Z_CREAR_TRANS_VENTAS_SIDER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_TRANS_VENTAS_SIDERResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse Z_CREAR_TRANS_VENTAS_SIDERResponse;
        
        public Z_CREAR_TRANS_VENTAS_SIDERResponse1() {
        }
        
        public Z_CREAR_TRANS_VENTAS_SIDERResponse1(SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse Z_CREAR_TRANS_VENTAS_SIDERResponse) {
            this.Z_CREAR_TRANS_VENTAS_SIDERResponse = Z_CREAR_TRANS_VENTAS_SIDERResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_GASTOS_VENTAS_SIDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPIRET2[] iT_RETURNField;
        
        private string i_TRANSPORTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] IT_RETURN {
            get {
                return this.iT_RETURNField;
            }
            set {
                this.iT_RETURNField = value;
                this.RaisePropertyChanged("IT_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_TRANSPORTE {
            get {
                return this.i_TRANSPORTEField;
            }
            set {
                this.i_TRANSPORTEField = value;
                this.RaisePropertyChanged("I_TRANSPORTE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CREAR_GASTOS_VENTAS_SIDERResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_GASTOField;
        
        private BAPIRET2[] iT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string E_GASTO {
            get {
                return this.e_GASTOField;
            }
            set {
                this.e_GASTOField = value;
                this.RaisePropertyChanged("E_GASTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] IT_RETURN {
            get {
                return this.iT_RETURNField;
            }
            set {
                this.iT_RETURNField = value;
                this.RaisePropertyChanged("IT_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_GASTOS_VENTAS_SIDERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDER Z_CREAR_GASTOS_VENTAS_SIDER;
        
        public Z_CREAR_GASTOS_VENTAS_SIDERRequest() {
        }
        
        public Z_CREAR_GASTOS_VENTAS_SIDERRequest(SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDER Z_CREAR_GASTOS_VENTAS_SIDER) {
            this.Z_CREAR_GASTOS_VENTAS_SIDER = Z_CREAR_GASTOS_VENTAS_SIDER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CREAR_GASTOS_VENTAS_SIDERResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse Z_CREAR_GASTOS_VENTAS_SIDERResponse;
        
        public Z_CREAR_GASTOS_VENTAS_SIDERResponse1() {
        }
        
        public Z_CREAR_GASTOS_VENTAS_SIDERResponse1(SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse Z_CREAR_GASTOS_VENTAS_SIDERResponse) {
            this.Z_CREAR_GASTOS_VENTAS_SIDERResponse = Z_CREAR_GASTOS_VENTAS_SIDERResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_DAMEPROVEEDORES_GGB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_PROVEEDORField;
        
        private string e_SOCIEDADField;
        
        private ZPROVEEDORGGB[] t_PROVEEDORESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string E_PROVEEDOR {
            get {
                return this.e_PROVEEDORField;
            }
            set {
                this.e_PROVEEDORField = value;
                this.RaisePropertyChanged("E_PROVEEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string E_SOCIEDAD {
            get {
                return this.e_SOCIEDADField;
            }
            set {
                this.e_SOCIEDADField = value;
                this.RaisePropertyChanged("E_SOCIEDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPROVEEDORGGB[] T_PROVEEDORES {
            get {
                return this.t_PROVEEDORESField;
            }
            set {
                this.t_PROVEEDORESField = value;
                this.RaisePropertyChanged("T_PROVEEDORES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_DAMEPROVEEDORES_GGBResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZPROVEEDORGGB[] t_PROVEEDORESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPROVEEDORGGB[] T_PROVEEDORES {
            get {
                return this.t_PROVEEDORESField;
            }
            set {
                this.t_PROVEEDORESField = value;
                this.RaisePropertyChanged("T_PROVEEDORES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_DAMEPROVEEDORES_GGBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGB Z_DAMEPROVEEDORES_GGB;
        
        public Z_DAMEPROVEEDORES_GGBRequest() {
        }
        
        public Z_DAMEPROVEEDORES_GGBRequest(SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGB Z_DAMEPROVEEDORES_GGB) {
            this.Z_DAMEPROVEEDORES_GGB = Z_DAMEPROVEEDORES_GGB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_DAMEPROVEEDORES_GGBResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse Z_DAMEPROVEEDORES_GGBResponse;
        
        public Z_DAMEPROVEEDORES_GGBResponse1() {
        }
        
        public Z_DAMEPROVEEDORES_GGBResponse1(SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse Z_DAMEPROVEEDORES_GGBResponse) {
            this.Z_DAMEPROVEEDORES_GGBResponse = Z_DAMEPROVEEDORES_GGBResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_SAPLETRA_GGBChannel : SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_SAPLETRA_GGBClient : System.ServiceModel.ClientBase<SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB>, SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB {
        
        public ZWS_SAPLETRA_GGBClient() {
        }
        
        public ZWS_SAPLETRA_GGBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_SAPLETRA_GGBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SAPLETRA_GGBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SAPLETRA_GGBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse1 SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB.Z_CREAR_PROVEEDOR_GGB(SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBRequest request) {
            return base.Channel.Z_CREAR_PROVEEDOR_GGB(request);
        }
        
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse Z_CREAR_PROVEEDOR_GGB(SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGB Z_CREAR_PROVEEDOR_GGB1) {
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBRequest inValue = new SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBRequest();
            inValue.Z_CREAR_PROVEEDOR_GGB = Z_CREAR_PROVEEDOR_GGB1;
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse1 retVal = ((SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_PROVEEDOR_GGB(inValue);
            return retVal.Z_CREAR_PROVEEDOR_GGBResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse1> SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB.Z_CREAR_PROVEEDOR_GGBAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBRequest request) {
            return base.Channel.Z_CREAR_PROVEEDOR_GGBAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBResponse1> Z_CREAR_PROVEEDOR_GGBAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGB Z_CREAR_PROVEEDOR_GGB) {
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBRequest inValue = new SGN.Negocio.WS_SAP_UNI.Z_CREAR_PROVEEDOR_GGBRequest();
            inValue.Z_CREAR_PROVEEDOR_GGB = Z_CREAR_PROVEEDOR_GGB;
            return ((SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_PROVEEDOR_GGBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse1 SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB.Z_CREAR_TRANS_VENTAS_SIDER(SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERRequest request) {
            return base.Channel.Z_CREAR_TRANS_VENTAS_SIDER(request);
        }
        
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse Z_CREAR_TRANS_VENTAS_SIDER(SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDER Z_CREAR_TRANS_VENTAS_SIDER1) {
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERRequest inValue = new SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERRequest();
            inValue.Z_CREAR_TRANS_VENTAS_SIDER = Z_CREAR_TRANS_VENTAS_SIDER1;
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse1 retVal = ((SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_TRANS_VENTAS_SIDER(inValue);
            return retVal.Z_CREAR_TRANS_VENTAS_SIDERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse1> SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB.Z_CREAR_TRANS_VENTAS_SIDERAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERRequest request) {
            return base.Channel.Z_CREAR_TRANS_VENTAS_SIDERAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERResponse1> Z_CREAR_TRANS_VENTAS_SIDERAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDER Z_CREAR_TRANS_VENTAS_SIDER) {
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERRequest inValue = new SGN.Negocio.WS_SAP_UNI.Z_CREAR_TRANS_VENTAS_SIDERRequest();
            inValue.Z_CREAR_TRANS_VENTAS_SIDER = Z_CREAR_TRANS_VENTAS_SIDER;
            return ((SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_TRANS_VENTAS_SIDERAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse1 SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB.Z_CREAR_GASTOS_VENTAS_SIDER(SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERRequest request) {
            return base.Channel.Z_CREAR_GASTOS_VENTAS_SIDER(request);
        }
        
        public SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse Z_CREAR_GASTOS_VENTAS_SIDER(SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDER Z_CREAR_GASTOS_VENTAS_SIDER1) {
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERRequest inValue = new SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERRequest();
            inValue.Z_CREAR_GASTOS_VENTAS_SIDER = Z_CREAR_GASTOS_VENTAS_SIDER1;
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse1 retVal = ((SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_GASTOS_VENTAS_SIDER(inValue);
            return retVal.Z_CREAR_GASTOS_VENTAS_SIDERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse1> SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB.Z_CREAR_GASTOS_VENTAS_SIDERAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERRequest request) {
            return base.Channel.Z_CREAR_GASTOS_VENTAS_SIDERAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERResponse1> Z_CREAR_GASTOS_VENTAS_SIDERAsync(SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDER Z_CREAR_GASTOS_VENTAS_SIDER) {
            SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERRequest inValue = new SGN.Negocio.WS_SAP_UNI.Z_CREAR_GASTOS_VENTAS_SIDERRequest();
            inValue.Z_CREAR_GASTOS_VENTAS_SIDER = Z_CREAR_GASTOS_VENTAS_SIDER;
            return ((SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB)(this)).Z_CREAR_GASTOS_VENTAS_SIDERAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse1 SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB.Z_DAMEPROVEEDORES_GGB(SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBRequest request) {
            return base.Channel.Z_DAMEPROVEEDORES_GGB(request);
        }
        
        public SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse Z_DAMEPROVEEDORES_GGB(SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGB Z_DAMEPROVEEDORES_GGB1) {
            SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBRequest inValue = new SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBRequest();
            inValue.Z_DAMEPROVEEDORES_GGB = Z_DAMEPROVEEDORES_GGB1;
            SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse1 retVal = ((SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB)(this)).Z_DAMEPROVEEDORES_GGB(inValue);
            return retVal.Z_DAMEPROVEEDORES_GGBResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse1> SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB.Z_DAMEPROVEEDORES_GGBAsync(SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBRequest request) {
            return base.Channel.Z_DAMEPROVEEDORES_GGBAsync(request);
        }
        
        public System.Threading.Tasks.Task<SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBResponse1> Z_DAMEPROVEEDORES_GGBAsync(SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGB Z_DAMEPROVEEDORES_GGB) {
            SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBRequest inValue = new SGN.Negocio.WS_SAP_UNI.Z_DAMEPROVEEDORES_GGBRequest();
            inValue.Z_DAMEPROVEEDORES_GGB = Z_DAMEPROVEEDORES_GGB;
            return ((SGN.Negocio.WS_SAP_UNI.ZWS_SAPLETRA_GGB)(this)).Z_DAMEPROVEEDORES_GGBAsync(inValue);
        }
    }
}
